# DS4DS Exercise Sheet 01

**General Instructions:**

- Review the weekly course material (lectures, readings, slides, etc.) before starting the exercises.
- Complete all assigned exercises independently before the Q&A session.
- Please use Julia Version 1.12.x to ensure compatibility.
- Please only write between the `#--- YOUR CODE STARTS HERE ---#` and `#--- YOUR CODE ENDS HERE ---#` comments.

We have the two matrices $A$, $B$:

$
A = \begin{bmatrix} 0 & 0 \\ 2 & 0 \end{bmatrix}, \\
B = \begin{bmatrix} 0 & -1 \\ 4 & 0 \end{bmatrix}
$

In [3]:
A = [0 0; 2 0]

B = [0 -1; 4 0]

2×2 Matrix{Int64}:
 0  -1
 4   0

### Task 1: Calculate the eigenvalues of the matrices $A$,$B$ and assign them to *eig_A* and *eig_B*
**Hint:** You should calculate them by hand and insert them here. Alternatively, you may solve this in Julia, but without the use of any extra packages.

In [7]:
eig_A = 0
eig_B = 0

### BEGIN SOLUTION
# 1. Calculate the trace (sum of diagonals) and determinant
trace_A = A[1,1] + A[2,2]
det_A = (A[1,1] * A[2,2]) - (A[1,2] * A[2,1])

# 2. Use the quadratic formula for the characteristic equation: λ² - tr(A)λ + det(A) = 0
discriminant = trace_A^2 - 4 * det_A

# 3. Calculate both eigenvalues (roots of the polynomial)
lambda_1 = (trace_A + sqrt(discriminant)) / 2
lambda_2 = (trace_A - sqrt(discriminant)) / 2

println("Eigenvalues of Matrix A: ", lambda_1, ", ", lambda_2)
eig_A = [lambda_1, lambda_2]

# Similarly, for matrix
trace_B = B[1,1] + B[2,2]
det_B = (B[1,1] * B[2,2]) - (B[1,2] * B[2,1])

# 2. Use the quadratic formula for the characteristic equation: λ² - tr(B)λ + det(B) = 0
discriminant = trace_B^2 - 4 * det_B

# 3. Calculate both eigenvalues (roots of the polynomial)
lambda_1 = (trace_B + sqrt(Complex(discriminant))) / 2
lambda_2 = (trace_B - sqrt(Complex(discriminant))) / 2

println("Eigenvalues of Matrix B: ", lambda_1, ", ", lambda_2)
eig_B = [lambda_1, lambda_2]
### END SOLUTION

Eigenvalues of Matrix A: 0.0, 0.0
Eigenvalues of Matrix B: 0.0 + 2.0im, 0.0 - 2.0im


2-element Vector{ComplexF64}:
 0.0 + 2.0im
 0.0 - 2.0im

### Task 2: Calculate the matrix exponential function of matrix A and B (by hand) [ exp(A\*t) and exp(B\*t) ]

**Hint 1:** You should calculate them by hand and insert them here. Alternatively, you may solve this in Julia, but without the use of any extra packages.

**Hint 2:** The function should at the end return a 2x2 matrix 

**Important: Don't use exp() function**

In [ ]:
#Here is an example how the functions should look like
function example(t)
    return [1*t 2; 3 4*t]
end

In [8]:
function matrixExponent(A, t)
    ### BEGIN SOLUTION
    
    # Initialize the result and the current term as the 2x2 Identity matrix
    result = [1.0 0.0; 0.0 1.0]
    term = [1.0 0.0; 0.0 1.0]
    
    # Run the Taylor Series expansion. 
    # Because A is nilpotent (A^2 = 0), this loop actually converges 
    # to the exact answer after just 1 iteration, but we can leave it 
    # at a higher number for consistency.
    for i in 1:50
        term = (term * A * t) / i
        result += term
    end
    
    return result
    ### END SOLUTION
end

matrixExponent (generic function with 1 method)

### Task 3: Calculate the system reactions $x(t)$ for a general $t$ and $x_0$

In [ ]:
x0 = [1; 1]

#Here is an example how the functions should look like. The function should at the end return a 2x1 vector
function example(t, x0)
    return [1 ; 2]
end

In [9]:
function state_response(t, A, x0)
    ### BEGIN SOLUTION
    return matrixExponent(t, A) * x0
    ### END SOLUTION
end

state_response (generic function with 1 method)

### Task 4: Plot the resulting time series with plots.jl for a given time interval into a common plot

Note: Take care of proper formatting of the plot. In particular, add correct axis labeling and a legend to be able to differentiate the time series.

In [ ]:
import Pkg
Pkg.add("Plots")
using Plots

    Updating registry at `C:\Users\27abd\.julia\registries\General.toml`
   Resolving package versions...
   Installed libdecor_jll ──────────────────────── v0.2.2+0
   Installed x265_jll ──────────────────────────── v4.1.0+0
   Installed OrdinaryDiffEqRKN ─────────────────── v1.5.0
   Installed JpegTurbo_jll ─────────────────────── v3.1.3+0
   Installed OrdinaryDiffEqStabilizedRK ────────── v1.4.0
   Installed libfdk_aac_jll ────────────────────── v2.0.4+0
   Installed Enzyme_jll ────────────────────────── v0.0.205+0
   Installed MutableArithmetics ────────────────── v1.6.7
   Installed Libmount_jll ──────────────────────── v2.41.2+0
   Installed GR_jll ────────────────────────────── v0.73.17+0
   Installed HypergeometricFunctions ───────────── v0.3.28
   Installed OrdinaryDiffEqRosenbrock ──────────── v1.18.1
   Installed LERC_jll ──────────────────────────── v4.0.1+0
   Installed ShowCases ─────────────────────────── v0.1.0
   Installed SciMLPublic ───────────────────────── v1.0.0
 

In [14]:
# time points
t_values = 0:0.01:5
N = size(t_values)[1]

x0 = [1; 1]

# fill with time series for matrix A and B respectively
xt_A = zeros((N, 2));
xt_B = zeros((N, 2))

501×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 ⋮    
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [15]:
### BEGIN SOLUTION
for i in 1:N
    xt_A[i, :] = state_response(t_values[i], A, x0)
    xt_B[i, :] = state_response(t_values[i], B, x0)
end
### END SOLUTION

In [16]:
# plot for A
# Extract state variables for system A
x1_A = xt_A[:, 1]
x2_A = xt_A[:, 2]

# Plot system A
plot(t_values, x1_A, label="x₁(t)", lw=2)
plot!(t_values, x2_A, label="x₂(t)", lw=2)

xlabel!("Time")
ylabel!("State Variables")
title!("State Response of System A")
plot!(grid = true)

UndefVarError: UndefVarError: `plot` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

In [ ]:
# plot for B
# Extract state variables for system B
x1_B = xt_B[:, 1]
x2_B = xt_B[:, 2]

# Plot system B
plot(t_values, x1_B, label="x₁(t)", lw=2)
plot!(t_values, x2_B, label="x₂(t)", lw=2)

xlabel!("Time")
ylabel!("State Variables")
title!("State Response of System B")
plot!(grid = true)